/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'
import { Route as GoalsGoalIdSessionStepIdRouteImport } from './routes/goals.$goalId.session.$stepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdSessionStepIdRoute =
  GoalsGoalIdSessionStepIdRouteImport.update({
    id: '/session/$stepId',
    path: '/session/$stepId',
    getParentRoute: () => GoalsGoalIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals/$goalId': typeof GoalsGoalIdRouteWithChildren
  '/goals/$goalId/session/$stepId': typeof GoalsGoalIdSessionStepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals/$goalId': typeof GoalsGoalIdRouteWithChildren
  '/goals/$goalId/session/$stepId': typeof GoalsGoalIdSessionStepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goals/$goalId': typeof GoalsGoalIdRouteWithChildren
  '/goals/$goalId/session/$stepId': typeof GoalsGoalIdSessionStepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goals/$goalId' | '/goals/$goalId/session/$stepId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goals/$goalId' | '/goals/$goalId/session/$stepId'
  id: '__root__' | '/' | '/goals/$goalId' | '/goals/$goalId/session/$stepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalsGoalIdRoute: typeof GoalsGoalIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId/session/$stepId': {
      id: '/goals/$goalId/session/$stepId'
      path: '/session/$stepId'
      fullPath: '/goals/$goalId/session/$stepId'
      preLoaderRoute: typeof GoalsGoalIdSessionStepIdRouteImport
      parentRoute: typeof GoalsGoalIdRoute
    }
  }
}

interface GoalsGoalIdRouteChildren {
  GoalsGoalIdSessionStepIdRoute: typeof GoalsGoalIdSessionStepIdRoute
}

const GoalsGoalIdRouteChildren: GoalsGoalIdRouteChildren = {
  GoalsGoalIdSessionStepIdRoute: GoalsGoalIdSessionStepIdRoute,
}

const GoalsGoalIdRouteWithChildren = GoalsGoalIdRoute._addFileChildren(
  GoalsGoalIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalsGoalIdRoute: GoalsGoalIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
